-- MySQL Script generated by MySQL Workbench
-- Mon 12 Nov 2018 06:49:30 PM CAT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema todoapp
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `todoapp` ;

-- -----------------------------------------------------
-- Schema todoapp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `todoapp` DEFAULT CHARACTER SET utf8mb4 ;
USE `todoapp` ;

-- -----------------------------------------------------
-- Table `todoapp`.`tasks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `todoapp`.`tasks` ;

CREATE TABLE IF NOT EXISTS `todoapp`.`tasks` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(32) NULL DEFAULT NULL,
  `description` VARCHAR(100) NULL DEFAULT NULL,
  `assignee` VARCHAR(32) NULL DEFAULT NULL,
  `date` DATETIME NULL DEFAULT NULL,
  `status` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
